# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#- task: AzureResourceGroupDeployment@2
#        displayName: 'Create or Update App Service'
#        inputs:
#          azureSubscription: '$(azureSubscription)'
#          resourceGroupName: '$(ResourceGroupName)'
#          location: '$(Location)'
#          csmFile: '$(System.DefaultWorkingDirectory)/infra/azuredeploy.json'
#          csmParametersFile: '$(System.DefaultWorkingDirectory)/infra/azuredeploy.parameters.json'
#          overrideParameters: '-application_name $(applicationName) -app_service_plan_sku S1 -server_administrator_Login "$(adminLogin)" -server_administrator_Login_Password $(password)'
#          deploymentOutputs: deploymentOutputs
