# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Nicks Internal Subscription'
  
  # Resource Group Name
  resourceGroupName: '$(applicationName)-rg'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#- task: AzureResourceGroupDeployment@2
#        displayName: 'Create or Update App Service'
#        inputs:
#          azureSubscription: '$(azureSubscription)'
#          resourceGroupName: '$(ResourceGroupName)'
#          location: '$(Location)'
#          csmFile: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
#          csmParametersFile: '$(System.DefaultWorkingDirectory)/azuredeploy.parameters.json'
#          overrideParameters: '-application_name $(applicationName) -clusterLoginUserName $(clusterLoginUserName) -clusterLoginPassword $(clusterLoginPassword) -sshUserName $(sshUserName) -sshPassword $(clusterLoginPassword) -KafkaRestProxyGroupName $(kafkaRestProxyGroupName) -KafkaRestProxyGroupId $(kafkaRestProxyGroupId)'
#          deploymentOutputs: deploymentOutputs
