# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Nicks Internal Subscription'
  
  # Resource Group Name
  resourceGroupName: '$(applicationName)-rg'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: deployCluster
    displayName: DeployCluster
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'nicks internal subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(ResourceGroupName)'
        location: '$(Location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/azuredeploy.parameters.json'
        overrideParameters: '-clusterName $(clusterName) -clusterLoginUserName $(clusterLoginUserName) -clusterLoginPassword $(clusterLoginPassword) -sshUserName $(sshUserName) -sshPassword $(clusterLoginPassword) -KafkaRestProxyGroupName $(kafkaRestProxyGroupName) -KafkaRestProxyGroupId $(kafkaRestProxyGroupId)'
        deploymentMode: 'Incremental'
        deploymentOutputs: deploymentOutputs

